---
- name: Create sftp users with disabled shell
  user:
    name: "{{ item }}"
    shell: /sbin/nologin
  when: sftp_users | length > 0
  loop: "{{ sftp_users }}"

- name: Ensure /home/USERNAME is owned by root
  file:
    path: "/home/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: sftp_users | length > 0
  loop: "{{ sftp_users }}"

- name: Create sftp directory for sftp users
  file:
    path: "/home/{{ item }}/sftp"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: sftp_users | length > 0
  loop: "{{ sftp_users }}"

- name: Create sftp upload directory for sftp users
  file:
    path: "/home/{{ item }}/sftp/upload"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0755
  when: sftp_users | length > 0
  loop: "{{ sftp_users }}"

- name: Set sftp subsystem to internal-sftp
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Subsystem\tsftp"
    line: "Subsystem\tsftp\tinternal-sftp"
    validate: /usr/sbin/sshd -T -f %s
    backup: yes
  notify: sshd_reload

- name: Add users to sshd chroot directive
  blockinfile:
    path: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -T -f %s
    backup: yes
    block: |
      Match User {{ sftp_users | join(',') }}
        ChrootDirectory /home/%u/sftp
        ForceCommand internal-sftp
        X11Forwarding no
        AllowTcpForwarding no
  when: sftp_users | length > 0
  notify: sshd_reload
